[2024-12-13T00:01:09.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-13T00:01:09.697+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.create_table scheduled__2024-12-12T00:00:00+00:00 [queued]>
[2024-12-13T00:01:09.705+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.create_table scheduled__2024-12-12T00:00:00+00:00 [queued]>
[2024-12-13T00:01:09.705+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-13T00:01:09.717+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-12 00:00:00+00:00
[2024-12-13T00:01:09.723+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=523) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-13T00:01:09.724+0000] {standard_task_runner.py:72} INFO - Started process 525 to run task
[2024-12-13T00:01:09.726+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'create_table', 'scheduled__2024-12-12T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmp29jq1cti']
[2024-12-13T00:01:09.728+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask create_table
[2024-12-13T00:01:09.786+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.create_table scheduled__2024-12-12T00:00:00+00:00 [running]> on host c8c82134bf48
[2024-12-13T00:01:10.046+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T00:00:00+00:00'
[2024-12-13T00:01:10.047+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-13T00:01:10.047+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-13T00:01:10.047+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2024-12-13 00:01:09.697350+00:00
[2024-12-13T00:01:10.047+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-13T00:01:10.048+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-13T00:01:10.048+0000] {sql.py:278} INFO - Executing:  
                        DROP TABLE  IF EXISTS Ecobalyse_table;
                        CREATE TABLE IF NOT EXISTS Ecobalyse_table(
                           
                                acd NUMERIC,
                                cch NUMERIC,
                                etf NUMERIC, 
                                etf-c NUMERIC, 
                                fru NUMERIC, 
                                fwe NUMERIC,
                                htc NUMERIC,
                                htc-c NUMERIC, 
                                htn NUMERIC,
                                htn-c NUMERIC,
                                ior NUMERIC,  
                                ldu NUMERIC, 
                                mru NUMERIC, 
                                ozd NUMERIC,
                                pco NUMERIC, 
                                pma NUMERIC,
                                swe NUMERIC,
                                tre NUMERIC,
                                wtu NUMERIC,
                                ecs NUMERIC, 
                                pef NUMERIC, 
                                airTransportRatio NUMERIC, 
                                business TEXT,
                                countryDyeing TEXT,
                                countryFabric TEXT,
                                countryMaking TEXT, 
                                countrySpinning TEXT, 
                                fabricProcess TEXT,
                                makingComplexity' TEXT, 
                                makingDeadStock NUMERIC,
                                makingWaste NUMERIC, 
                                mass NUMERIC,
                                numberOfReferences NUMERIC,
                                physicalDurability NUMERIC,
                                price NUMERIC, 
                                product TEXT,
                                surfaceMass NUMERIC, 
                                traceability BOOLEAN,
                                upcycled BOOLEAN,
                                yarnSize NUMERIC
                           
                           
                           
                           
                           ); 
                    
[2024-12-13T00:01:10.058+0000] {base.py:84} INFO - Retrieving connection 'ecobalyse_database_connection'
[2024-12-13T00:01:10.067+0000] {base.py:84} INFO - Retrieving connection 'ecobalyse_database_connection'
[2024-12-13T00:01:10.071+0000] {sql.py:544} INFO - Running statement:  
                        DROP TABLE  IF EXISTS Ecobalyse_table;
                        CREATE TABLE IF NOT EXISTS Ecobalyse_table(
                           
                                acd NUMERIC,
                                cch NUMERIC,
                                etf NUMERIC, 
                                etf-c NUMERIC, 
                                fru NUMERIC, 
                                fwe NUMERIC,
                                htc NUMERIC,
                                htc-c NUMERIC, 
                                htn NUMERIC,
                                htn-c NUMERIC,
                                ior NUMERIC,  
                                ldu NUMERIC, 
                                mru NUMERIC, 
                                ozd NUMERIC,
                                pco NUMERIC, 
                                pma NUMERIC,
                                swe NUMERIC,
                                tre NUMERIC,
                                wtu NUMERIC,
                                ecs NUMERIC, 
                                pef NUMERIC, 
                                airTransportRatio NUMERIC, 
                                business TEXT,
                                countryDyeing TEXT,
                                countryFabric TEXT,
                                countryMaking TEXT, 
                                countrySpinning TEXT, 
                                fabricProcess TEXT,
                                makingComplexity' TEXT, 
                                makingDeadStock NUMERIC,
                                makingWaste NUMERIC, 
                                mass NUMERIC,
                                numberOfReferences NUMERIC,
                                physicalDurability NUMERIC,
                                price NUMERIC, 
                                product TEXT,
                                surfaceMass NUMERIC, 
                                traceability BOOLEAN,
                                upcycled BOOLEAN,
                                yarnSize NUMERIC
                           
                           
                           
                           
                           ); 
                    , parameters: None
[2024-12-13T00:01:10.072+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "-"
LINE 8:                                 etf-c NUMERIC, 
                                           ^

[2024-12-13T00:01:10.089+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-13T00:01:10.090+0000] {logging_mixin.py:190} INFO - Task start:2024-12-13 00:01:09.697350+00:00 end:2024-12-13 00:01:10.089051+00:00 duration:0.391701
[2024-12-13T00:01:10.090+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-12 00:00:00+00:00: scheduled__2024-12-12T00:00:00+00:00, state:running, queued_at: 2024-12-13 00:00:00.190954+00:00. externally triggered: False>
[2024-12-13T00:01:10.090+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "-"
LINE 8:                                 etf-c NUMERIC, 
                                           ^
[2024-12-13T00:01:10.091+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ecobalyse_dag, task_id=create_table, run_id=scheduled__2024-12-12T00:00:00+00:00, execution_date=20241212T000000, start_date=20241213T000109, end_date=20241213T000110
[2024-12-13T00:01:10.105+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-13T00:01:10.106+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 156 for task create_table (syntax error at or near "-"
LINE 8:                                 etf-c NUMERIC, 
                                           ^
; 525)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "-"
LINE 8:                                 etf-c NUMERIC, 
                                           ^

[2024-12-13T00:01:10.140+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-13T00:01:10.161+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-13T00:01:10.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
