[2024-12-12T20:08:20.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T20:08:20.606+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.load_json_file scheduled__2024-12-11T00:00:00+00:00 [queued]>
[2024-12-12T20:08:20.610+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.load_json_file scheduled__2024-12-11T00:00:00+00:00 [queued]>
[2024-12-12T20:08:20.610+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-12T20:08:20.742+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_json_file> on 2024-12-11 00:00:00+00:00
[2024-12-12T20:08:20.747+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-12T20:08:20.748+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2024-12-12T20:08:20.750+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'load_json_file', 'scheduled__2024-12-11T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmpwo94tz6p']
[2024-12-12T20:08:20.751+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask load_json_file
[2024-12-12T20:08:20.808+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.load_json_file scheduled__2024-12-11T00:00:00+00:00 [running]> on host c67d6daee869
[2024-12-12T20:08:20.891+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='load_json_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-11T00:00:00+00:00'
[2024-12-12T20:08:20.892+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-12T20:08:20.892+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-12T20:08:20.892+0000] {logging_mixin.py:190} INFO - Current task name:load_json_file state:running start_date:2024-12-12 20:08:20.606447+00:00
[2024-12-12T20:08:20.892+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-12T20:08:20.892+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T20:08:20.893+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_json_file() missing 1 required positional argument: 'filename'
[2024-12-12T20:08:20.902+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-12T20:08:20.903+0000] {logging_mixin.py:190} INFO - Task start:2024-12-12 20:08:20.606447+00:00 end:2024-12-12 20:08:20.902502+00:00 duration:0.296055
[2024-12-12T20:08:20.903+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_json_file> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-11 00:00:00+00:00: scheduled__2024-12-11T00:00:00+00:00, state:running, queued_at: 2024-12-12 20:06:14.478571+00:00. externally triggered: False>
[2024-12-12T20:08:20.903+0000] {logging_mixin.py:190} INFO - Failure caused by load_json_file() missing 1 required positional argument: 'filename'
[2024-12-12T20:08:20.903+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ecobalyse_dag, task_id=load_json_file, run_id=scheduled__2024-12-11T00:00:00+00:00, execution_date=20241211T000000, start_date=20241212T200820, end_date=20241212T200820
[2024-12-12T20:08:20.910+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T20:08:20.910+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task load_json_file (load_json_file() missing 1 required positional argument: 'filename'; 268)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_json_file() missing 1 required positional argument: 'filename'
[2024-12-12T20:08:20.922+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-12T20:08:20.932+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T20:08:20.932+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
